[package]
name = "rust-interop-with-cpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "rust_interop_with_cpp"
crate-type = ["staticlib"]
